version: '3.4'
services:
  sqlserverdb:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Secret1234"
    ports:
        - '1434:1433'
    restart: always
    volumes:
        - './drive:/var/opt/mssql'

  mongodb:
    image: mongo:latest
    ports:
        - 27017:27017
    volumes:
        - './mongo_data_container:/data/db'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  
